### ISSUE TITLE
Modify Standards Grading template

### ISSUE THREAD

**Issue by jibarnum** [heliophysicsPy/heliophysicsPy.github.io#101]
PyHC package developers have asked if the grading template could be updated, or the metadata updated, such that it could include links to the docs, contributing guide, etc.

**Comment by sapols** [comment]
https://github.com/heliophysicsPy/heliophysicsPy.github.io/issues/95

**Comment by sapols** [comment]
Pasting a copy of the grading template here so I can alter it:

This is based on the [PyHC Project Review Guidelines](https://github.com/heliophysicsPy/heliophysicsPy.github.io/blob/master/_pyhc_projects/pyhc_project_grading_guidelines.md). Numbers in square brackets refer to the item in the [PyHC Standards](https://github.com/heliophysicsPy/standards/blob/master/standards.md).

1. Community
- [ ] All code is available and developed publicly [2]
- [ ] Code is not duplicated [12]
- [ ] The package is not forked from an existing project [12]
- [ ] Package provides contribution guidelines [13]
- [ ] Package has a code of conduct [15]

2. Documentation
- [ ] All functions, classes, and modules have documentation strings (docstrings) provided in a standard conventions (e.g. numpydoc) [8]
- [ ] High level documentation is provided as guides, tutorials, and developer docs [8]
- [ ] Documentation is provided in version control with the code [8]
- [ ] Documentation is available online in a readable form [8]

3. Testing
- [ ] Package has unit tests of individual components (e.g. functions, classes) [9]
- [ ] Package has integration tests that test the interaction between components that covers most of the code [9]
- [ ] Testing coverage is measured [9]

4. Software Maturity
- [ ] All code is organized and provided as part of installable Python packages [1]
- [ ] All code uses version control [6]
- [ ] Projects adopts the basic style recommendations of PEP 8 [7]

5. Python 3
- [ ] Package is compatible with python 3 [11]

6. License
- [ ] Project has a license [5]
- [ ] Project has a permissive license for open source scientific software [5]

**Comment by sapols** [comment]
My changes:

 - Under Software Maturity, added points for 3, 4, 10, and 14 from the standards doc.

**Comment by sapols** [comment]
@jibarnum is this the "Contributing Guide"? https://github.com/heliophysicsPy/heliophysicsPy.github.io/blob/master/_pyhc_projects/adding_to_pyhc_project_list.md

I wanna make sure I'm linking to the right thing.

**Comment by sapols** [comment]
Okay, @jibarnum I can't think of any other ways I could modify this to improve it. Was there anything else that was specifically requested? This now includes links to the docs and contributing guide, but I don't know if I missed anything under "etc."

**Comment by jibarnum** [comment]
@sapols Yes, you identified the correct Contributing Guide, as well as seem to have captured what I remember other developers discussing improving.
