### ISSUE TITLE
Shawn is not an admin

### ISSUE THREAD

**Issue by sapols** [heliophysicsPy/heliophysicsPy.github.io#125]
Shawn Polson (@sapols) is tech lead for PyHC so it'd make sense for him to be a GitHub admin.

**Comment by jibarnum** [comment]
I believe I just gave you the correct permissions, let me know if it's still not working. I believe you should've gotten an email invite? Let me know if that's not the case.

**Comment by sapols** [comment]
> I believe I just gave you the correct permissions, let me know if it's still not working. I believe you should've gotten an email invite? Let me know if that's not the case.

Yep, that worked! I can see the Settings tab in the repo and everything now. Thank you.
Now let's see if I can update our DNS and stop those emails from sending each time we build...
