### ISSUE TITLE
Custom domain is pointed at an outdated IP address

### ISSUE THREAD

**Issue by sapols** [heliophysicsPy/heliophysicsPy.github.io#126]
As shown in the picture below, we have some kind of DNS misconfiguration. Reading [the](https://docs.github.com/en/github/working-with-github-pages/troubleshooting-custom-domains-and-github-pages#dns-misconfiguration) [documentation](https://docs.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain), it seems that GitHub doesn't manage this. So I don't know how to fix it. GitHub recommends contacting our DNS provider but I don't know who that is (although a `dig` command suggests it's dreamhost.com). The warning message shown in the picture gets emailed to us each time the repo builds, so it'd be nice to correct it.

![Screen Shot 2020-09-15 at 12 45 35 PM](https://user-images.githubusercontent.com/14846863/93251492-7e347480-f751-11ea-8b92-951ab07bef91.png)

**Comment by sapols** [comment]
@ehsteve do you any insight into this?

**Comment by sapols** [comment]
@ehsteve do you have any insight into this?

**Comment by ehsteve** [comment]
Hey @sapols sorry for taking so long to see this! Just looked into this and I'm not sure what the problem is though I'll admit that this is not my strong suit. The site seems to be working properly. I do own the domain and therefore administer it and pay for it. In the short term, I could add someone to help administer. In the long to medium term, I'd like to divest myself of the domain. I set it up early on and wanted to grab the domain for the community. I never thought that I should own it personally.

**Comment by ehsteve** [comment]
Also, it would be good to go to using https. That would mean getting an SSL certificate. I did not want to lock us into using a free let's encrypt certificate if there is a more appropriate path depending on who would own the domain.

**Comment by Cadair** [comment]
github will do ssl for you if you configure it right. This issue implies that the A records need updating.

**Comment by sapols** [comment]
No worries, @ehsteve, thanks for getting back! And thanks for the comment, @Cadair, I agree. Do you have someone in mind to help administer, Steve? I think my PyHC tech lead role makes me an acceptable person to take over the domain, if that's something you'd like to discuss.

Switching to HTTPS with GitHub is as simple as checking the `Enforce HTTPS` checkbox at the bottom of the screenshot in this ticket description (once we clear the error). I recently went through the site and fixed all the mixed content, so presumably, the only thing standing in our way there is updating the A records.

**Comment by sapols** [comment]
@ehsteve I just sent you an email to your @nasa.gov address.

**Comment by Cadair** [comment]
damn it I have access to this but forgot it was on dreamhost

**Comment by sapols** [comment]
@Cadair thank you. Let me know if I can help.

**Comment by Cadair** [comment]
records  updated, should be propagating, you should also be able to admin this

**Comment by sapols** [comment]
@Cadair that worked! 🙏 GitHub is no longer giving us those error messages and they are in the process of issuing our certificate. I'll close this issue soon.

**Comment by ehsteve** [comment]
Just saw this now. I hope that what I just did did not screw up what you did on dreamhost @Cadair!

**Comment by sapols** [comment]
It didn't. This issue is still resolved. 😌
