### ISSUE TITLE
Enforce HTTPS

### ISSUE THREAD

**Issue by sapols** [heliophysicsPy/heliophysicsPy.github.io#132]
Update our site from HTTP to HTTPS. Our site URL will change from

http://heliopython.org

to

https://heliopython.org

Then we'll have to update all our documentation accordingly. From that point on, adding mixed content to the site (i.e. anything served over HTTP) will be discouraged.

**Comment by Cadair** [comment]
If you click the enforce button then at least it's only external content we need to worry about.

**Comment by sapols** [comment]
Indeed. And the only mixed content we've had recently were a couple project logos with image files that came from HTTP URLs. That'll be easy to avoid.

**Comment by sapols** [comment]
Done.
