### ISSUE TITLE
Add geopack project to our Projects Page

### ISSUE THREAD

**Issue by jibarnum** [heliophysicsPy/heliophysicsPy.github.io#159]
Github repo located [here](https://github.com/tsssss/geopack). Requested by Bob Weigel.

**Comment by sapols** [comment]
@jibarnum who would we put as the contact person? It's not obvious to me looking at the repo if any PyHC member is associated with geopack.

**Comment by jibarnum** [comment]
@sapols Good question... let me ask Bob if he knows, since he requested the addition.

**Comment by jibarnum** [comment]
@sapols actually, based on the README, it appears this is the info: Author: Sheng Tian, Univ. of Minnesota, tianx138@umn.edu

**Comment by sapols** [comment]
@jibarnum I saw the Author was Sheng Tian, but he's not a PyHC member. Or he's not listed on our People page, at least. Is there a precedent for including non-PyHC developers as contacts on our Projects page?

**Comment by jibarnum** [comment]
@sapols ah... well. That's different. Hmmmm, I"m not sure actually if we have a precedent for this or not. It does seem sketch to add a non-PyHC member's project to our page, then expect them to be willing to field questions/participate in our group. Maybe this is a good topic to touch on at our next telecon and discuss with the group.

**Comment by sapols** [comment]
@jibarnum Good call. Let's bring it up at the next telecon.
