### ISSUE TITLE
Project cards do not render nicely on mobile

### ISSUE THREAD

**Issue by wtbarnes** [heliophysicsPy/heliophysicsPy.github.io#19]
The project descriptions are not readable on mobile as the cards become too narrow and the text gets cutoff on the right-hand side.

**EDIT:** I realize I'm creating a lot of issues. I'm happy to help fix these as well! Just creating issues so I don't forget about them!

**Comment by wtbarnes** [comment]
Closed by #23

**Comment by ehsteve** [comment]
@Cadair ping. The project cards are too damn big.

**Comment by Cadair** [comment]
They are, I think it's probably worth reformatting the site to follow what we do for sunpy.org as we have a cards sphinx plugin on our sunpy.org/team page etc.

**Comment by wtbarnes** [comment]
Do people still think the cards are too big? I'm not sure what the solution is here. On mobile, we cannot fit more than one card width wise and we cannot squash in height without changing the aspect ratio so I'm not sure how they could be smaller unless we dropped the card images altogether on mobile

**Comment by Cadair** [comment]
Could you just limit the max width so it's not 100% page width?
