### ISSUE TITLE
Create web page for PyHC Spring 2022 meeting

### ISSUE THREAD

**Issue by jibarnum** [heliophysicsPy/heliophysicsPy.github.io#199]
Once more, feel free to recycle past meeting templates. Dates are Monday, May 16 - Thursday, May 19, 9-11 AM MT. We'll be using the same zoom as usual (this is an all-virtual event).

Some general brainstorming notes I've made:
Day 1: Project Updates (Core projects, a couple 2020 HDEE wrap ups)
Day 2: Hackathon Brainstorming (focused on tutorials involving multiple PyHC packages --> this is a great precursor to the Summer School event!); Other Presentations (TBD)
Day 3: Hackathons
Day 4: Hackathon results; Other Related Presentations/Discussions (TBD); Wrap Ups (emphasize upcoming Summer School!)

**Comment by sapols** [comment]
Done in this PR: https://github.com/heliophysicsPy/heliophysicsPy.github.io/pull/213
