### ISSUE TITLE
Improve webpage support for twitter

### ISSUE THREAD

**Issue by rstoneback** [heliophysicsPy/heliophysicsPy.github.io#204]
When I tweeted a link to the PyHC Summer School page, https://heliopython.org/summer-school, the tweet doesn't render well.

<img width="602" alt="Screen Shot 2022-02-14 at 2 25 07 PM" src="https://user-images.githubusercontent.com/3595641/153941123-2802f752-f5fc-4088-afe5-01db4b1c6912.png">

For comparison, here is a tweet to the pysat GitHub page.

<img width="603" alt="image" src="https://user-images.githubusercontent.com/3595641/153941276-8d931eb6-3ace-4f0e-98f3-fe8808f69b9a.png">

I think some elements can be added to the PyHC summer school page so twitter knows what to put into the tweet box area. First thought would be the PyHC logo.

**Comment by jibarnum** [comment]
Tried following suggestions in [this link](https://brianbunke.com/blog/2017/09/06/twitter-cards-on-jekyll/#tweak-to-fit-your-needs), but couldn't quite get it to work. See my work in julie_fix_twitter for reference.

**Comment by jibarnum** [comment]
Okay, I figured out that twitter cards won't render relative/absolute paths in a repo, only URLs. I tried replacing "title_image" in _config.yml with the perma link to the PyHC logo in our repo.... no dice. But the website isn't broken by having once more merged my `julie_fix_twitter` branch into main, so leaving it for the moment.

**Comment by jibarnum** [comment]
Too many URL options. 😅 But hey, it worked! I'm going to go ahead and close this ticket out. I've merged everything from that test branch to main. @rstoneback your twitter link should look better now!
