### ISSUE TITLE
Add some more details to Summer School page

### ISSUE THREAD

**Issue by jibarnum** [heliophysicsPy/heliophysicsPy.github.io#222]
We've received some questions recently, whose answers should probably be included on the summer school page for others to see as well. These include:
- Will most of the other attendees being using the same hotel?
- Where's a good place to get food near the hotel?
- Exactly where is the bus pickup location and what is its schedule?
- Do I need a pass to take the bus? If so, how do I get it?
- What room are we meeting at ESAC?
- Which presenters are going to be on-site vs remote
    - Astropy: in-person
    - SunPy: in-person
    - PlasmaPy: remote
    - HAPI: in-person
    - pySPEDAS: remote
    - pysat: in-person
    - Kamodo: in-person
    - Speasy: in-person
    - OMMBV: in-person 

All but the last question we're waiting on Arnaud for that info.

We should also mention that we're recording presentations for later viewing/streaming to YouTube. I'm looking into a Slack space option as well, for attendees to connect and chat.

**Comment by jibarnum** [comment]
Updated schedule here:  https://docs.google.com/spreadsheets/d/1WR3gKiBlMCFmuRBI7JvUL9CE8J-0uNSRBg_FOCiFD-c/edit#gid=0

**Comment by sapols** [comment]
[PR](https://github.com/heliophysicsPy/heliophysicsPy.github.io/pull/223) open. I chose to leave out whether most attendees will be using the same hotel because it's impossible to say, and also suggestions about where to get food because people can google that themselves.
