### ISSUE TITLE
Wrong link in README.md

### ISSUE THREAD

**Issue by jgieseler** [heliophysicsPy/heliophysicsPy.github.io#224]
I think the link in the README.md under [Add software package](https://github.com/heliophysicsPy/heliophysicsPy.github.io#add-software-package=) points to a wrong repo (i.e., to a fork instead to the original). That is,
```
Fork [this repo](https://github.com/scivision/heliophysicsPy.github.io) on GitHub.
```
should be
```
Fork [this repo](https://github.com/heliophysicsPy/heliophysicsPy.github.io) on GitHub.
```

**Comment by sapols** [comment]
Thanks for catching this! Fixed.
