### ISSUE TITLE
Create a ROR ID for PyHC and add it to the website with citation instructions

### ISSUE THREAD

**Issue by namurphy** [heliophysicsPy/heliophysicsPy.github.io#243]
According to the [DOI FAQ](https://www.doi.org/faq.html), it's possible to assign a DOI to "any entity — physical, digital or abstract — that you wish to identify".  We could perhaps assign a DOI to the Python in Heliophysics Community itself!  That way, we'd be able to cite PyHC directly, instead of citing an article or a website as a proxy to PyHC.  Were we to do that, we would then want to add the DOI to the website alongside citation instructions.  This would be particularly useful to do in the next few weeks if we wanted to be able to cite PyHC directly in heliophysics decadal papers which are due in mid-August.

I'm not sure how to go about assigning a DOI to things, but we did include a few citations to funding agencies in [PlasmaPy's CodeMeta file](https://github.com/PlasmaPy/PlasmaPy/blob/d3b597ae6babf6a6092a6c676ff2fe64191a5d5e/codemeta.json#L19) as examples.

**Comment by HelioAnalytics** [comment]
@namurphy The coming decadal is a good point!  I think it would be really good to have a way to cite PyHC in general.

**Comment by sapols** [comment]
We're getting a ROR ID instead of a DOI. It's a human-led process, not automated, so we're tracking the process here: https://github.com/ror-community/ror-updates/issues/1513

**Comment by namurphy** [comment]
@sapols just announced on the mailing list that the [ROR ID](https://ror.org/) for PyHC is now: **https://ror.org/012prn105**

We still need to add it to the website, I think.

**Comment by sapols** [comment]
@namurphy 100% agree. I’m on holiday though so it’ll happen after the new year. 👍

**Comment by jibarnum** [comment]
@sapols can we go ahead and close this ticket?
