### ISSUE TITLE
Add link to gallery

### ISSUE THREAD

**Issue by ehsteve** [heliophysicsPy/heliophysicsPy.github.io#27]
Need to have a link to the gallery from the website.

**Comment by ehsteve** [comment]
How about we rename the contact tab to "Help" like we do on sunpy.org? Then we could put it there?

**Comment by ehsteve** [comment]
Or create a tab Link directly to it. @Cadair was going to theme the gallery to match. Thinking about it further this is my preferred fix.

**Comment by wtbarnes** [comment]
Looks like this was resolved by #28
