### ISSUE TITLE
Adding a member

### ISSUE THREAD

**Issue by jmbhughes** [heliophysicsPy/heliophysicsPy.github.io#299]
How does one become a member on the website (https://heliopython.org/people/)? I can open a PR to add myself, but I wasn't sure if there were more requirements. Since I have a project listed (with more on the way), I'd like to be listed. I will try to attend more meetings, but sometimes it's difficult because of conflicts. Thanks!

**Comment by sapols** [comment]
Good question! I don't know that we document this well anywhere. There's no formal process beyond opening a PR to add yourself to `_data/members.yml`. I certainly count you as a member, so if you want to open that PR I'll merge it.

**Comment by jmbhughes** [comment]
Done! Thanks!
