### ISSUE TITLE
Link Zenodo community from webpage?

### ISSUE THREAD

**Issue by jtniehof** [heliophysicsPy/heliophysicsPy.github.io#301]
I don't think our Zenodo community at <https://zenodo.org/communities/heliopython/> is linked from the website...maybe put a link under Documents and/or Projects? We could then also update the project addition instructions to include information on linking GitHub to Zenodo and asking to be put in the Zenodo community. (Or maybe that's an Informational PHEP...)

**Comment by sapols** [comment]
Thanks for the suggestion! It shouldn't have taken me this long but I finally did it. Our Zenodo is now linked to in the [Documents](https://heliopython.org/docs/) page.

I'm not too keen on mentioning Zenodo in the project addition instructions yet, even though it's a good idea and getting every PyHC package in Zenodo is on my roadmap. However, this is the best use case for an Informational PHEP I've seen yet, so I think it'd be neat to try to make it one.
