### ISSUE TITLE
Remove "Python 3" category from Projects page?

### ISSUE THREAD

**Issue by namurphy** [heliophysicsPy/heliophysicsPy.github.io#330]
It's been over four years since the sunset of Python 2.7, so it might be time to remove the "Python 3" category on the [Projects](https://heliopython.org/projects/) page.  

At the moment, there are only two projects that have "needs improvement" under Python 3.

**Comment by jtniehof** [comment]
Even without any updates to policy (PHEP3 and such), I don't think this column is of use to our users, and can probably be hidden from display immediately.
