### ISSUE TITLE
Examples tab doesn't have link back to main page

### ISSUE THREAD

**Issue by jibarnum** [heliophysicsPy/heliophysicsPy.github.io#56]
All the other tabs on the PyHC website retain the bar at the top of the page that links to other tabs/the main website.

**Comment by ehsteve** [comment]
This is actually a bug that has to be resolved on a different repo namely https://github.com/heliophysicsPy/gallery

**Comment by jibarnum** [comment]
> This is actually a bug that has to be resolved on a different repo namely https://github.com/heliophysicsPy/gallery

Ah, alright, I'll check and see if this issue is listed there. If not, I'll add it as a ticket. :) Thanks!
