### ISSUE TITLE
Fix intermittent test failues regarding mixed HTTP/HTTPS content

### ISSUE THREAD

**Issue by namurphy** [heliophysicsPy/heliophysicsPy.github.io#85]
We've been getting some intermittent test failures associated with mixing HTTP content into our HTTPS-enabled site.

```
Mixed content detected

Although you have enabled HTTPS on your site, we’ve detected some content that’s still being served over an HTTP connection.

In projects/index.html:

    img http://optics.gi.alaska.edu/optics/sites/default/files/logo.png
    img http://themis.ssl.berkeley.edu/gbo/thm_gbo_logo.png
```

**Comment by sapols** [comment]
I’m thinking it should be a goal to move the site entirely to HTTPS. I want to look into doing that as a fix for this issue.

**Comment by sapols** [comment]
The mixed content has been updated. I'll switch the whole site to HTTPS soon.
