### ISSUE TITLE
certificate issue?

### ISSUE THREAD

**Issue by michaelaye** [heliophysicsPy/heliophysicsPy.github.io#93]
Following the link in the README gives me this:

<img width="785" alt="Screenshot 2020-04-07 13 52 21" src="https://user-images.githubusercontent.com/69774/78713198-1e4ebd80-78d7-11ea-97bf-ee0f7cce2c44.png">

**Comment by sapols** [comment]
@michaelaye Do you still get this warning when you follow the link? I don't seem to get it.

**Comment by michaelaye** [comment]
Yes:

![image](https://user-images.githubusercontent.com/69774/87569121-e8fafe00-c683-11ea-82b6-f36fb51558c2.png)

**Comment by michaelaye** [comment]
note, i use the link in the README, not the forced http link you gave above.

**Comment by michaelaye** [comment]
to be absolutely clear, i'm talking about the link in this README: https://github.com/heliophysicsPy/heliophysicsPy.github.io/blob/master/README.md

**Comment by sapols** [comment]
Oh I see. Yep, I was able to replicate this. That link sure does embed a URL with httpS, which it shouldn't. I'll fix it. Do you not get that warning when you click my link that forces http? Hopefully you don't and all that's needed is to fix that link in the README. Sorry it took so long to address this.

**Comment by sapols** [comment]
@michaelaye I fixed that README. Please let me know if that resolves this issue.

**Comment by michaelaye** [comment]
No worries, not an often used link anyhow I guess. But having an http based website is of course getting old fast, I have heard chatter starting to block ALL of http based websites by default in browsers in the near future? Not sure I remember it right, but it's certainly becoming an oddity these days to not support https.

**Comment by sapols** [comment]
I’m with you. Moving the site to HTTPS should be a goal.
