### ISSUE TITLE
Package reveiw template

### ISSUE THREAD

**Issue by dstansby** [heliophysicsPy/heliophysicsPy.github.io#95]
This is a draft holding place for the package review template. **It is a work in progress**.

This is based on the [PyHC Project Review Guidelines](https://github.com/heliophysicsPy/heliophysicsPy.github.io/blob/master/_pyhc_projects/pyhc_project_grading_guidelines.md). Numbers in square brackets refer to the item in the [PyHC Standards](https://github.com/heliophysicsPy/standards/blob/master/standards.md).

1. Community
- [ ] All code is available and developed publicly [2]
- [ ] Code is not duplicated [12]
- [ ] The package is not forked from an existing project [12]
- [ ] Package provides contribution guidelines [13]
- [ ] Package has a code of conduct [15]

2. Documentation
- [ ] All functions, classes, and modules have documentation strings (docstrings) provided in a standard conventions (e.g. numpydoc) [8]
- [ ] High level documentation is provided as guides, tutorials, and developer docs [8]
- [ ] Documentation is provided in version control with the code [8]
- [ ] Documentation is available online in a readable form [8]

3. Testing
- [ ] Package has unit tests of individual components (e.g. functions, classes) [9]
- [ ] Package has integration tests that test the interaction between components that covers most of the code [9]
- [ ] Testing coverage is measured [9]

4. Software Maturity
- [ ] All code is organized and provided as part of installable Python packages [1]
- [ ] All code uses version control [6]
- [ ] Projects adopts the basic style recommendations of PEP 8 [7]

5. Python 3
- [ ] Package is compatible with python 3 [11]

6. License
- [ ] Project has a license [5]
- [ ] Project has a permissive license for open source scientific software [5]

**Comment by wtbarnes** [comment]
Should this be a PR template?

**Comment by jklenzing** [comment]
In the review guidelines, Software Maturity also includes points 3, 4, 10, and 14 from the standards doc.  Are we including those at this point?  Asking as this affects the self-review for sami2py (and other codes).

**Comment by jibarnum** [comment]
I like this a lot! I'll talk to Tom to go about incorporating this template more permanently.

**Comment by sapols** [comment]
_**My final version after modifying it in #101:**_

This is based on the [PyHC Project Review Guidelines](https://github.com/heliophysicsPy/heliophysicsPy.github.io/blob/master/_pyhc_projects/pyhc_project_grading_guidelines.md). Numbers in square brackets refer to the item in the [PyHC Standards](https://github.com/heliophysicsPy/standards/blob/master/standards.md). See the [Contributing Guide](https://github.com/heliophysicsPy/heliophysicsPy.github.io/blob/master/_pyhc_projects/adding_to_pyhc_project_list.md) for instructions to add a project to the PyHC Project List.

1. Community
- [ ] All code is available and developed publicly [[2](https://github.com/heliophysicsPy/standards/blob/master/standards.md#standards)]
- [ ] Code is not duplicated [[12](https://github.com/heliophysicsPy/standards/blob/master/standards.md#standards)]
- [ ] The package is not forked from an existing project [[12](https://github.com/heliophysicsPy/standards/blob/master/standards.md#standards)]
- [ ] Package provides contribution guidelines [[13](https://github.com/heliophysicsPy/standards/blob/master/standards.md#standards)]
- [ ] Package has a code of conduct [[15](https://github.com/heliophysicsPy/standards/blob/master/standards.md#standards)]

2. Documentation
- [ ] All functions, classes, and modules have documentation strings (docstrings) provided in a standard conventions (e.g. [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html)) [[8](https://github.com/heliophysicsPy/standards/blob/master/standards.md#standards)]
- [ ] High level documentation is provided as guides, tutorials, and developer docs [[8](https://github.com/heliophysicsPy/standards/blob/master/standards.md#standards)]
- [ ] Documentation is provided in version control with the code [[8](https://github.com/heliophysicsPy/standards/blob/master/standards.md#standards)]
- [ ] Documentation is available online in a readable form [[8](https://github.com/heliophysicsPy/standards/blob/master/standards.md#standards)]

3. Testing
- [ ] Package has unit tests of individual components (e.g. functions, classes) [[9](https://github.com/heliophysicsPy/standards/blob/master/standards.md#standards)]
- [ ] Package has integration tests that test the interaction between components that covers most of the code [[9](https://github.com/heliophysicsPy/standards/blob/master/standards.md#standards)]
- [ ] Testing coverage is measured [[9](https://github.com/heliophysicsPy/standards/blob/master/standards.md#standards)]

4. Software Maturity
- [ ] All code is organized and provided as part of installable Python packages [[1](https://github.com/heliophysicsPy/standards/blob/master/standards.md#standards)]
- [ ] Project has consistent and stable releases [[3](https://github.com/heliophysicsPy/standards/blob/master/standards.md#standards)]
- [ ] Project releases are available through [PyPI](https://pypi.org) and [Conda](https://docs.conda.io/en/latest/) [[3](https://github.com/heliophysicsPy/standards/blob/master/standards.md#standards)]
- [ ] Unstable code has a release number less than 1.0 (e.g. 0.x) [[3](https://github.com/heliophysicsPy/standards/blob/master/standards.md#standards)]
- [ ] Project supports all major operating systems (MacOS, Linux, Windows) [[4](https://github.com/heliophysicsPy/standards/blob/master/standards.md#standards)]
- [ ] All code uses version control [[6](https://github.com/heliophysicsPy/standards/blob/master/standards.md#standards)]
- [ ] Projects adopts the basic style recommendations of [PEP 8](https://www.python.org/dev/peps/pep-0008/) [[7](https://github.com/heliophysicsPy/standards/blob/master/standards.md#standards)]
- [ ] Project imports the minimum number of packages necessary [[10](https://github.com/heliophysicsPy/standards/blob/master/standards.md#standards)]
- [ ] Binary files are added to the package repository only when necessary [[14](https://github.com/heliophysicsPy/standards/blob/master/standards.md#standards)]

5. Python 3
- [ ] Package is compatible with python 3 [[11](https://github.com/heliophysicsPy/standards/blob/master/standards.md#standards)]

6. License
- [ ] Project has a license [[5](https://github.com/heliophysicsPy/standards/blob/master/standards.md#standards)]
- [ ] Project has a permissive license for open source scientific software [[5](https://github.com/heliophysicsPy/standards/blob/master/standards.md#standards)]

**Comment by sapols** [comment]
The package review template has been added for real:
https://github.com/heliophysicsPy/heliophysicsPy.github.io/blob/master/_pyhc_projects/package_review_template.md
